name: Manage App Service Network Access
description: Manages network access to the Azure App Service
inputs:
  app-service-name:
    description: "App Service Name"
    required: true
  resource-group-name:
    description: "Resource Group Name for the App Service"
    required: true
  github-runner-ip:
    description: "IP address of the current GitHub runner"
    required: true
  enable-network-access:
    description: "Enable or disable network access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Enable Public Network Access
      if: ${{ inputs.enable-network-access == 'true' }}
      shell: bash
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group-name }}
        APP_SERVICE_NAME: ${{ inputs.app-service-name }}
      run: |
        az webapp update \
          --resource-group "$RESOURCE_GROUP" \
          --name "$APP_SERVICE_NAME" \
          --set publicNetworkAccess=Enabled > /dev/null

    - name: Add Access Restriction Rule
      if: ${{ inputs.enable-network-access == 'true' }}
      shell: bash
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group-name }}
        APP_SERVICE_NAME: ${{ inputs.app-service-name }}
        GITHUB_RUNNER_IP: ${{ inputs.github-runner-ip }}
      run: |
        az webapp config access-restriction add \
          --resource-group "$RESOURCE_GROUP" \
          --name "$APP_SERVICE_NAME" \
          --rule-name github-runner-ip \
          --action Allow \
          --ip-address "$GITHUB_RUNNER_IP" \
          --priority 100 > /dev/null

    - name: Remove Access Restriction Rule
      if: ${{ inputs.enable-network-access == 'false' }}
      shell: bash
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group-name }}
        APP_SERVICE_NAME: ${{ inputs.app-service-name }}
      run: |
        az webapp config access-restriction remove \
          --resource-group "$RESOURCE_GROUP" \
          --name "$APP_SERVICE_NAME" \
          --rule-name github-runner-ip \
          --action Allow > /dev/null

    - name: Disable Public Network Access
      if: ${{ inputs.enable-network-access == 'false' }}
      shell: bash
      env:
        RESOURCE_GROUP: ${{ inputs.resource-group-name }}
        APP_SERVICE_NAME: ${{ inputs.app-service-name }}
      run: |
        az webapp update \
          --resource-group "$RESOURCE_GROUP" \
          --name "$APP_SERVICE_NAME" \
          --set publicNetworkAccess=Disabled > /dev/null
