name: Manage App Service Network Access
description: Manages network access to the Azure App Service
inputs:
  app-service-name:
    description: "App Service Name"
    required: true
  resource-group-name:
    description: "Resource Group Name for the App Service"
    required: true
  github-runner-ip:
    description: "IP address of the current GitHub runner"
    required: true
  enable-network-access:
    description: "Enable or disable network access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Enable Public Network Access
      if: ${{ inputs.enable-network-access == 'true' }}
      shell: bash
      run: |
        az webapp update \
          --resource-group ${{ inputs.resource-group-name }} \
          --name ${{ inputs.app-service-name }} \
          --set publicNetworkAccess=Enabled > /dev/null

    - name: Add Access Restriction Rule
      if: ${{ inputs.enable-network-access == 'true' }}
      shell: bash
      run: |
        az webapp config access-restriction add \
          --resource-group ${{ inputs.resource-group-name }} \
          --name ${{ inputs.app-service-name }} \
          --rule-name github-runner-ip \
          --action Allow \
          --ip-address ${{ inputs.github-runner-ip }} \
          --priority 100 > /dev/null

    - name: Remove Access Restriction Rule
      if: ${{ inputs.enable-network-access == 'false' }}
      shell: bash
      run: |
        az webapp config access-restriction remove \
          --resource-group ${{ inputs.resource-group-name }} \
          --name ${{ inputs.app-service-name }} \
          --rule-name github-runner-ip \
          --action Allow > /dev/null

    - name: Disable Public Network Access
      if: ${{ inputs.enable-network-access == 'false' }}
      shell: bash
      run: |
        az webapp update \
          --resource-group ${{ inputs.resource-group-name }} \
          --name ${{ inputs.app-service-name }} \
          --set publicNetworkAccess=Disabled > /dev/null

    - name: Sleep 40s
      shell: bash
      run: |
        sleep 40
