---
name: Run regression tests
on:
  workflow_dispatch:

jobs:
  build-test-scan:
    name: Build image and regression test
    runs-on: ubuntu-latest
    environment: dev
    env:
      CPD_GOOGLEANALYTICSTAG: ${{secrets.TF_VAR_CPD_GOOGLEANALYTICSTAG}}
      CPD_SPACE_ID: ${{secrets.TF_VAR_CPD_SPACE_ID}}
      CPD_PREVIEW_KEY: ${{secrets.TF_VAR_CPD_PREVIEW_KEY}}
      CPD_DELIVERY_KEY: ${{secrets.TF_VAR_CPD_DELIVERY_KEY}}
      CPD_CLARITY: ${{secrets.TF_VAR_CPD_CLARITY}}
      CPD_FEATURE_POLLING_INTERVAL: 0 
      CPD_INSTRUMENTATION_CONNECTIONSTRING: ""
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker App Image
        run: cd Childrens-Social-Care-CPD; docker build . --file Dockerfile --tag childrens-social-care-cpd:ContainerizeRegressionTests
        
      - name: Run the regression tests
        run: cd browser-tests/regression-tests; docker-compose up --exit-code-from regression-tests

      - uses: actions/upload-artifact@v4
        name: Playwright report
        if: always()
        with:
          name: playwright-report
          retention-days: 7
          path: |
            ${{ github.workspace }}/browser-tests/regression-tests/playwright-report
      
      - name: Run Tidy up
        if: always()
        run: cd browser-tests/regression-tests; docker-compose down --volumes      