name: Docker Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: dev
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout Release Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set GitHub Runner IP
        run: echo "GITHUB_RUNNER_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Enable Network Access for ACR
        uses: ./.github/actions/manage-acr-network-access
        with:
          acr-name: "${{ secrets.REGISTRY_NAME }}"
          resource-group-name: "${{ secrets.APP_RESOURCE_GROUP_NAME }}"
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.REGISTRY_NAME }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: Childrens-Social-Care-CPD
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
          build-args: |
            VCSREF=${{ github.sha }}
            VCSTAG=${{ env.RELEASE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Cosign
        if: false
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "latest"

      - name: Sign Docker Image
        if: false
        run: cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
        env:
          COSIGN_EXPERIMENTAL: "true"

      - name: Disable Network Access for ACR
        uses: ./.github/actions/manage-acr-network-access
        with:
          acr-name: "${{ secrets.REGISTRY_NAME }}"
          resource-group-name: "${{ secrets.APP_RESOURCE_GROUP_NAME }}"
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false
